name: ğŸ“¦ Bump Version & Create Release

on:
  push:
    branches:
      - main

jobs:
  bump-and-release:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to push version bump + create release

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"  # Not GITHUB_TOKEN!

    #   - name: âš™ï¸ Set up Git identity
    #     run: |
    #       git config --global user.name "github-actions[bot]"
    #       git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: ğŸš€ Bump version & generate changelog
        id: cz
        uses: commitizen-tools/commitizen-action@5b0848cd060263e24602d1eba03710e056ef7711 # 0.24.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          changelog_increment_filename: body.md

      - name: ğŸ“ Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body_path: body.md
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
